export default {
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',
  CHOOSE_LEAGUE: 'CHOOSE_LEAGUE',
  UPDATE_PORTFOLIOS: 'UPDATE_PORTFOLIOS',
  INITIALIZE_PORTFOLIOS: 'INITIALIZE_PORTFOLIOS',
};
