export default {
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_USER: 'REGISTER_USER',
  CHOOSE_LEAGUE: 'CHOOSE_LEAGUE',
  UPDATE_PORTFOLIOS: 'UPDATE_PORTFOLIOS',
  INITIALIZE_PORTFOLIOS_AND_LEAGUE: 'INITIALIZE_PORTFOLIOS_AND_LEAGUE',
  UPDATE_LEAGUE: 'UPDATE_LEAGUE',
};
